# Enable recommended Flutter lints
analyzer:
  errors:
    use_build_context_synchronously: ignore
include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Tambahan rules yang umum dan berguna
    prefer_single_quotes: true
    avoid_print: false
    always_declare_return_types: true
    avoid_unnecessary_containers: true
    prefer_const_constructors: true
    prefer_final_locals: true
    use_key_in_widget_constructors: true
    sized_box_for_whitespace: true

# Tips:
# Gunakan `flutter analyze` untuk mengecek error & warning dari lint.
